
GET http://127.0.0.1:8080/people/
Content-Type: application/json

###

POST http://127.0.0.1:8080/people/
Content-Type: application/json

{
    "name": "Stefan",
    "age": 42,
    "role": "ADMIN"
}
###

POST http://127.0.0.1:8080/people/
Content-Type: application/json

{
    "name": "David",
    "age": 42,
    "role": "ADMIN"
}
###

DELETE http://127.0.0.1:8080/people/ea2066916a4e5e79459a4506188362235ad7d5e684ee0c7ba4d128a7
Content-Type: application/json

###

GET http://127.0.0.1:8080/people/bd056a715e1df81f66be816ed4c15be84f2a8d33f94919eebc3e1b2f
Content-Type: application/json

###
GET http://127.0.0.1:8080/people/1a
Content-Type: application/json

###
GET http://127.0.0.1:8080/people/1
Content-Type: application/json

###
GET http://127.0.0.1:8080/people/zz
Content-Type: application/json
