POST http://127.0.0.1:8081/
Content-Type: application/json

{
    "name": "Stefan",
    "age": 42,
    "role": "ADMIN"
}

###
GET http://127.0.0.1:8081/bd056a715e1df81f66be816ed4c15be84f2a8d33f94919eebc3e1b2f
Content-Type: application/json

###
GET http://127.0.0.1:8081/1a
Content-Type: application/json

###
GET http://127.0.0.1:8081/1
Content-Type: application/json

###
GET http://127.0.0.1:8081/zz
Content-Type: application/json

